const fs=require('fs'),path=require('path'),D=__dirname;
const css=`
@import url('https://fonts.googleapis.com/css2?family=Montserrat:wght@600;700;800&family=Nunito+Sans:ital,wght@0,400;0,600;0,700;1,400&family=JetBrains+Mono:wght@400;500&display=swap');
:root{--indigo:#4F46E5;--indigo-dark:#4338CA;--indigo-soft:#EEF0FE;--indigo-line:#DDE1FB;--laranja:#F97316;--laranja-soft:#FFF3E8;--verde:#10B981;--verde-dark:#047857;--verde-soft:#ECFDF5;--vermelho:#EF4444;--vermelho-dk:#B91C1C;--vermelho-sf:#FEF2F2;--amarelo:#EAB308;--amarelo-dk:#A16207;--amarelo-sf:#FEFCE8;--tinta:#1E293B;--tinta-clara:#475569;--cinza:#64748B;--borda:#E2E8F0;--prompt-bg:#151F38;--prompt-bg2:#1B2745;--prompt-txt:#E8EDF7;--d:'Montserrat',sans-serif;--f:'Nunito Sans',sans-serif;--i:#1E293B;--b:#4F46E5;--o:#F97316;--t:#10B981;--l:#E2E8F0}
body{font-family:var(--f)!important;color:var(--tinta)!important;background:#fff!important;font-size:10.6pt!important;line-height:1.62!important}.page{background:#fff!important}.page:after{color:var(--cinza)!important;font-family:var(--d)!important}.cover{background:linear-gradient(150deg,#EEF0FE 0%,#F6F4FF 45%,#FFF8F0 100%)!important;border-radius:22px!important;border:0!important;text-align:center;align-items:center}.ey{font-family:var(--d)!important;color:var(--indigo)!important}.cover h1,h1,h2,h3{font-family:var(--d)!important;color:var(--tinta)!important}.cover h1 em,h2{color:var(--indigo)!important}.lead{color:var(--tinta-clara)!important}.tag{color:var(--indigo)!important;border-color:var(--indigo-line)!important;background:#fff!important;font-family:var(--d)!important}.card{border-color:var(--borda)!important;border-radius:12px!important;box-shadow:0 4px 14px rgba(15,23,42,.035)!important}.card.teal,.teal{background:var(--verde-soft)!important;border-color:#A7F3D0!important}.card.orange,.orange{background:var(--laranja-soft)!important;border-color:#FED7AA!important}.card.red,.red{background:var(--vermelho-sf)!important;border-color:#FECACA!important}.card.blue,.blue{background:var(--indigo-soft)!important;border-color:var(--indigo-line)!important}.prompt{background:linear-gradient(160deg,var(--prompt-bg),var(--prompt-bg2))!important;color:var(--prompt-txt)!important;font-family:'JetBrains Mono',monospace!important}.activity{background:var(--laranja-soft)!important;border-left-color:var(--laranja)!important}.case{background:var(--indigo-soft)!important;border-color:var(--indigo-line)!important}.bad{background:var(--vermelho-sf)!important;border-color:#FECACA!important}.good{background:var(--verde-soft)!important;border-color:#A7F3D0!important}.table th{background:var(--indigo-soft)!important;color:var(--indigo-dark)!important;font-family:var(--d)!important}.table td,.table th{border-color:var(--borda)!important}.figure{border-color:var(--borda)!important}.slide{background:#FCFCFE!important}.slide:before{width:100%!important;height:9px!important;background:var(--indigo)!important}.slide:after{color:var(--cinza)!important;font-family:var(--d)!important}.slide h1{font-family:var(--d)!important;color:var(--tinta)!important}.slide .lead{color:var(--tinta-clara)!important}.timer,.cronometro{background:var(--laranja)!important;color:#fff!important}.app-controls{background:rgba(15,23,42,.94)!important}.app-controls button:hover{background:var(--indigo)!important}.app-bar{background:linear-gradient(90deg,var(--indigo),var(--laranja))!important}.thumb span{color:var(--indigo)!important}
.caso{background:linear-gradient(135deg,#F5F3FF,#EEF0FE)!important;border-color:#C7D2FE!important}.duelo{background:#FCFCFE!important;border-color:var(--indigo-line)!important}.caca{background:#FFFBEB!important;border-color:#FCD34D!important}.celular{background:linear-gradient(135deg,#ECFDF5,#D1FAE5)!important;border-color:#6EE7B7!important}.desafio{background:linear-gradient(135deg,#FFF7ED,#FFEDD5)!important;border-color:#FB923C!important}.saida{background:linear-gradient(150deg,#EEF0FE,#F5F3FF)!important;border-color:var(--indigo-line)!important}.selo{background:var(--indigo)!important;font-family:var(--d)!important}.titulo{font-family:var(--d)!important;color:var(--tinta)!important}.tempo{color:var(--laranja)!important;font-family:var(--d)!important}.cena{border-left-color:var(--laranja)!important}.solucao{border-left-color:var(--verde)!important}.instrucao{color:var(--amarelo-dk)!important}
`;
for(const file of ['Apostila_IA_para_Empreendedores_2026.html','Slides_IA_para_Empreendedores_2026.html']){
 const f=path.join(D,file);let h=fs.readFileSync(f,'utf8');h=h.replace('</style>',css+'</style>');fs.writeFileSync(f,h,'utf8');
}
console.log('Identidade de Educadores aplicada: Montserrat/Nunito, índigo #4F46E5, laranja #F97316 e componentes correspondentes.');
