const fs=require('fs'),path=require('path'),D=__dirname;
const A=[
['1','A loja que responde tudo no WhatsApp','Sexta-feira, 18h. Marina tem 37 mensagens não respondidas: tamanho, troca, prazo e preço. Ela responde cada pessoa de um jeito e alguns clientes desistem antes de comprar.','Em dupla, criem seis perguntas de FAQ e decidam o que pode ser rascunho, o que precisa de dado atualizado e o que exige atendimento humano.','Crie um FAQ para [LOJA], com respostas de até 240 caracteres. Marque [CONFIRMAR] para estoque, preço e prazo. Para reclamação ou troca excepcional, encaminhe para uma pessoa responsável.','A IA não deve prometer estoque, prazo ou exceção. O resultado útil é FAQ + regra de escalonamento.','Uma tarefa em 5 minutos','Escolha uma tarefa que você repete toda semana. Escreva um prompt C.O.F.R.E., gere uma primeira versão, revise um fato e salve o resultado.','A fonte que parece real','A IA informou: “Segundo o Relatório Nacional de Varejo Local 2025, 83,7% dos clientes abandonam a compra quando não recebem resposta em 10 minutos.”','O número exato, o título plausível e a ausência de link são sinais de alerta. Não use dado, citação ou estatística sem localizar a fonte primária.','Primeiro uso no celular','Abra a IA que você já possui acesso. Cole um prompt para transformar uma mensagem de cliente em resposta cordial. Remova nome, telefone e pedido real antes de colar.','Prompt C.O.F.R.E. salvo, uma tarefa revisada e uma regra de segurança para a equipe.'],
['2','O salão sem tempo para postar','Joana só publica quando sobra tempo. Terça a quinta têm horários vazios, mas ela não quer baixar preço nem prometer resultado de procedimento.','Planejem sete dias de conteúdo: dúvida, bastidor, prova autorizada, convite e recuperação de agenda. Cada peça deve ter CTA e dado a confirmar.','Monte calendário de 7 dias para [NEGÓCIO]. Objetivo: [OBJETIVO]. Para cada dia: formato, ideia, CTA e campo [CONFIRMAR]. Não invente agenda, resultado ou desconto.','Calendário só funciona se houver responsável, horário de publicação e confirmação de disponibilidade.','Calendário em 7 minutos','Crie sete ideias a partir de uma dúvida real de cliente. Escolha apenas uma para publicar nesta semana e defina a métrica.','O antes e depois não autorizado','A IA sugere usar a foto de uma cliente para comprovar resultado, sem perguntar se existe autorização nem se a imagem foi alterada.','Imagem, depoimento e resultado exigem autorização. Use exemplos próprios autorizados ou marque [INSERIR PROVA AUTORIZADA].','Teste no celular: conteúdo útil','Crie uma legenda para responder a uma dúvida real do seu público. Antes de publicar, confirme promessa, preço, agenda e consentimento de qualquer imagem.','Calendário de 7 dias, uma campanha pequena e uma métrica de conversas qualificadas.'],
['3','A imobiliária que perde leads','Rafael recebe contatos pelo site, Instagram e WhatsApp. A equipe responde rápido, mas não registra estágio, bairro, prazo ou próximo passo.','Criem cinco perguntas de diagnóstico, três respostas-modelo e uma regra clara de passagem para o corretor.','Estruture proposta para [SERVIÇO] usando somente [DADOS CONFIRMADOS]. Inclua objetivo, entregas, cronograma, investimento [VALOR], exclusões e próximo passo. Marque lacunas como [CONFIRMAR].','Diagnóstico vem antes da proposta. Documento, renda detalhada e dados de terceiros não entram em ferramenta sem autorização.','Proposta revisável em 5 minutos','Use dados fictícios para montar a estrutura de uma proposta. Destaque três campos que uma pessoa precisa confirmar antes de enviar.','O imóvel que a IA garantiu','Uma resposta pronta afirma que determinado imóvel está disponível e aceita visita, sem consultar o sistema de estoque.','Disponibilidade muda. Toda resposta deve conter [CONSULTAR ESTOQUE] até alguém validar no sistema autorizado.','Teste no celular: follow-up útil','Crie um follow-up que faça uma pergunta de diagnóstico ou entregue uma prova útil. Não use pressão falsa nem invente disponibilidade.','Proposta-base, macro de atendimento e próximo follow-up com valor real.'],
['4','O restaurante que automatizou antes de validar','Um formulário recebe pedido com alergia grave. O fluxo automático responde “pedido confirmado”, embora ninguém tenha checado ingredientes ou capacidade da cozinha.','Redesenhem o fluxo: em que ponto ele para, quem recebe o alerta e qual texto seguro informa o cliente?','Desenhe piloto de automação para [PROCESSO]. Gatilho: [GATILHO]. Ações: [AÇÕES]. Liste dados proibidos, exceções, aprovação humana, métrica e modo de teste. Nunca inclua credenciais.','Exceções críticas interrompem automação e acionam pessoa responsável. Piloto começa com poucos casos e nunca envia decisão irreversível.','Piloto em 5 minutos','Desenhe um fluxo de três passos que apenas cria rascunho e notifica responsável. Defina um ponto explícito de revisão humana.','A senha no prompt','O manual da equipe recomenda colar token de acesso e lista de clientes em um chat para “configurar rápido” uma automação.','Credenciais e dados pessoais não entram no prompt. Guarde acessos no cofre apropriado e use dados fictícios no teste.','Teste no celular: plano de 30 dias','Registre uma tarefa, o responsável, a métrica e a data da primeira revisão. Comece pelo fluxo mais simples e reversível.','Plano de IA da empresa, piloto de 30 dias e primeira revisão agendada.']
];
const css='.caso,.duelo,.caca,.celular,.desafio,.saida,.destacavel{page-break-inside:avoid;margin:14px 0;border-radius:15px;padding:17px 20px}.caso{background:linear-gradient(135deg,#F5F3FF,#EEF0FE);border:2px solid #C7D2FE}.duelo{background:#FCFCFE;border:2px solid #C7D2FE}.caca{background:#FFFBEB;border:2px solid #FCD34D}.celular{background:linear-gradient(135deg,#ECFDF5,#D1FAE5);border:2px solid #6EE7B7}.desafio{background:linear-gradient(135deg,#FFF7ED,#FFEDD5);border:2px solid #FB923C}.saida{background:linear-gradient(135deg,#EEF0FE,#F5F3FF);border:2px solid #C7D2FE}.cabeca{display:flex;gap:10px;align-items:center;margin-bottom:10px}.selo,.cronometro{background:#246bfd;color:white;border-radius:999px;padding:5px 11px;font:800 8.5pt Arial}.cronometro{background:#f97316;font-size:14pt;border-radius:10px}.titulo{font:800 12pt Arial;color:#132a4a}.tempo{margin-left:auto;color:#f97316;font:800 9pt Arial}.cena,.resposta-ia,.solucao{background:#fff;border-radius:10px;padding:12px 14px;line-height:1.55}.cena{border-left:4px solid #f97316}.solucao{border-left:4px solid #0d9488;margin-top:10px}.instrucao{font-weight:800;color:#92400e}.linhas .lin{height:18px;border-bottom:1px dashed #94a3b8}.premium-activities h2{color:#246bfd}.premium-activities .prompt{font-size:8.7pt}.saida .item{border-bottom:1px solid #dbe3fa;padding:6px 0}.saida .item:last-child{border:0}.app-slide .caso,.app-slide .duelo,.app-slide .caca,.app-slide .celular,.app-slide .desafio,.app-slide .saida{font-size:16px}.app-slide .cronometro{font-size:28px}';
const esc=s=>s.replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));
const lines=n=>'<div class="linhas">'+Array(n||4).fill('<div class="lin"></div>').join('')+'</div>';
function block(x){
 const n=x[0],caso='<div class="caso"><div class="cabeca"><span class="selo">CASO '+n+'</span><span class="titulo">'+x[1]+'</span><span class="tempo">10 min · em duplas</span></div><div class="cena">'+x[2]+'</div><p class="instrucao">Missão: '+x[3]+'</p>'+lines(4)+'<div class="solucao"><b>Debrief do formador</b><p>'+x[5]+'</p></div></div>';
 const duelo='<div class="duelo"><div class="cabeca"><span class="selo" style="background:#f97316">DUELO '+n+'</span><span class="titulo">Do pedido vago ao pedido revisável</span><span class="tempo">7 min</span></div><p><b>Prompt C.O.F.R.E. para comparar:</b></p><div class="prompt">'+esc(x[4])+'</div><p class="instrucao">Sua vez: adapte ao seu negócio e inclua uma restrição que evite erro caro.</p>'+lines(3)+'</div>';
 const des='<div class="desafio"><div class="cabeca"><span class="cronometro">05:00</span><span class="titulo">'+x[6]+'</span></div><p>'+x[7]+'</p><ol><li>Defina contexto e objetivo.</li><li>Especifique formato e limite.</li><li>Gere uma versão.</li><li>Revise antes de salvar.</li></ol></div>';
 const caca='<div class="caca"><div class="cabeca"><span class="selo" style="background:#d97706">CAÇA AO ERRO '+n+'</span><span class="titulo">'+x[8]+'</span><span class="tempo">4 min</span></div><div class="resposta-ia">'+x[9]+'</div><p class="instrucao">O que está perigoso ou incompleto? Como você corrigiria antes de usar?</p>'+lines(3)+'<div class="solucao"><b>Gabarito comentado</b><p>'+x[10]+'</p></div></div>';
 const cel='<div class="celular"><div class="cabeca"><span class="selo" style="background:#0d9488">NO CELULAR</span><span class="titulo">'+x[11]+'</span><span class="tempo">5 min</span></div><p>'+x[12]+'</p></div>';
 const saida='<div class="saida"><div class="titulo">Antes de ir embora — o que você leva hoje</div><div class="item">☐ Produto do encontro salvo</div><div class="item">☐ Dados, fatos e promessas revisados</div><div class="item">☐ Responsável e próxima revisão definidos</div><div class="item">☐ '+x[13]+'</div></div>';
 return {book:'<section class="page premium-activities"><div class="ey">ENCONTRO '+n+' · EXPERIÊNCIAS PRÁTICAS</div><h2>Praticar, revisar e levar para a empresa</h2>'+caso+duelo+des+caca+cel+saida+'</section>',slides:[caso,duelo,des,caca,cel,saida].map((q,i)=>'<section class="slide"><div class="ey">ENCONTRO '+n+' · ATIVIDADE '+(i+1)+'</div><h1>'+['Estudo de caso','Duelo de prompt','Desafio cronometrado','Caça ao erro','Teste no celular','Saída com produto'][i]+'</h1>'+q+'</section>').join('')};
}
let book=fs.readFileSync(path.join(D,'Apostila_IA_para_Empreendedores_2026.html'),'utf8');
book=book.replace('</style>',css+'</style>').replace('</body>',A.map(block).map(x=>x.book).join('')+'</body>');
fs.writeFileSync(path.join(D,'Apostila_IA_para_Empreendedores_2026.html'),book,'utf8');
let deck=fs.readFileSync(path.join(D,'Slides_IA_para_Empreendedores_2026.html'),'utf8');
deck=deck.replace('</style>',css+'</style>').replace('</body>',A.map(block).map(x=>x.slides).join('')+'</body>');
fs.writeFileSync(path.join(D,'Slides_IA_para_Empreendedores_2026.html'),deck,'utf8');
console.log('Componentes premium inseridos: 4 casos, 4 duelos, 4 desafios, 4 caças ao erro, 4 testes no celular e 4 saídas.');
