const fs=require('fs'),path=require('path'),puppeteer=require('../IA Professores/node_modules/puppeteer');
const D=__dirname,md=fs.readFileSync(path.join(D,'PROMPTS_DE_IMAGENS_COMPLETOS.md'),'utf8');
const rows=[...md.matchAll(/^###\s+([^\n]+)\n+\n+([\s\S]*?)(?=\n###|$)/gm)].map((m,i)=>({n:i+1,file:m[1].trim(),prompt:m[2].trim()}));
const esc=s=>s.replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));
const style='@import url("https://fonts.googleapis.com/css2?family=Montserrat:wght@600;700;800&family=Nunito+Sans:wght@400;600;700&family=JetBrains+Mono&display=swap");@page{size:A4;margin:14mm}body{font-family:"Nunito Sans",Arial;color:#1E293B}.pg{page-break-after:always}.n{display:inline-block;background:#4F46E5;color:white;border-radius:99px;padding:6px 12px;font:800 9pt Montserrat}.f{font:700 14pt "JetBrains Mono";margin:14px 0 5px;color:#4338CA}.p{white-space:pre-wrap;background:#F5F3FF;border-left:5px solid #F97316;border-radius:8px;padding:16px;line-height:1.62}.meta{color:#64748B}h1{font:800 25pt Montserrat;color:#4338CA}';
const parts=rows.map(x=>'<section class="pg"><span class="n">'+x.n+'</span><div class="f">'+esc(x.file)+'</div><p class="meta">Destino: Curso_IA_Empreendedores_2026\\imagens\\'+esc(x.file)+'</p><div class="p">'+esc(x.prompt)+'</div></section>').join('');
const html='<!doctype html><meta charset="utf-8"><style>'+style+'</style><body><section class="pg"><h1>Prompts fotográficos</h1><p>IA para Empreendedores. Gere fotografia editorial documental fotorrealista, sem texto, logotipos ou interfaces legíveis, e salve cada arquivo com o nome indicado.</p></section>'+parts+'</body>';
fs.writeFileSync(path.join(D,'Prompts_das_Imagens.html'),html,'utf8');
(async()=>{const b=await puppeteer.launch({headless:'new',args:['--no-sandbox']});const p=await b.newPage();await p.goto('file:///'+path.join(D,'Prompts_das_Imagens.html').replace(/\\/g,'/'),{waitUntil:'domcontentloaded'});const target=path.join(D,'Prompts_das_Imagens_NEON.pdf');await p.pdf({path:target,format:'A4',printBackground:true,margin:{top:0,bottom:0,left:0,right:0}});await b.close();console.log(rows.length+' prompts exportados: '+path.basename(target))})().catch(e=>{console.error(e);process.exit(1)});
